DIR_DISPLAY_SRC = ./display_driver/src
DIR_DISPLAY_INC = ./display_driver/inc
DIR_DISPLAY_TEST = ./display_driver

LIB=-Wl,--gc-sections
LIB += -lwirinPi -lm

TARGET = epd
CC = gcc
MSG = -g -O -ffunction-sections -fdata-sections -Wall
CFLAGS += $(MSG) 

TEST:
echo "TES"

